name: ar_augmented_faces
description: Flutter Plugin for creating Augmented Reality Augmented Faces experiences - Supports ARKit for iOS and ARCore for Android devices.
version: 0.7.1
repository: https://github.com/dalves96/ar_augmented_faces

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^11.4.0
  json_annotation: ^4.9.0
  geolocator: ^13.0.2
#  geolocator_web: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  plugin:
    platforms:
      android:
        package: io.carius.lars.ar_augmented_faces
        pluginClass: ArFlutterPlugin
      ios:
        pluginClass: ArFlutterPlugin
